version: '3'
services:
  sccbroker:
    #network_mode: host
    image: scc-broker_sccbroker:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SCC_STATE_SERVER_HOST: 127.0.0.1
      SCC_BROKER_SERVER_PORT: 8888
      SOCKETCLUSTER_BROKER_SSL_KEY: ssl/certificate.key
      SOCKETCLUSTER_BROKER_SSL_CERT: ssl/certificate.csr
      SOCKETCLUSTER_WS_ENGINE: ws
    volumes:
      - '.:/usr/src'
    ports:
      - '8888:8888'
    command: npm start
